version: '3'
services:
  rabbitmq:
    image: jadesky/rabbitmq:3.11-delayed-message
    container_name: rabbitmq-delayed-message
    ports:
     - 127.0.0.1:5672:5672
     - 127.0.0.1:15672:15672
    environment:
     - RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins
     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
     - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
     - ecom_network

networks:
  ecom_network:
    name: ecom_network
    external: true
