version: '3.9'
services:
  redis:
    image: redis/redis-stack:edge
    container_name: redis-stack
    ports:
     - 6379:6379
    environment:
     - REDIS_ARGS=--appendonly no --save ""
    ciommand: 'redis-server --requirepass ${REDIS_PASSWORD}'    
    volumes:
     - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
     - ecom_network
       
networks:
  ecom_network:
    name: ecom_network
    external: true
